name: Bug Report
description: Report a bug or unexpected behaviour
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Fill out the information below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: What went wrong? Give a concise and sufficient description.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the erroneous behaviour.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, browser, version, etc.
      placeholder: macOS 14, Chrome 121
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional info.
      description: Logs, screenshots, or other relevant details.
    validations:
      required: false
