name: Feature Request
description: Suggest a new feature or extension
title: "[Feature]: "
labels: ["feature"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution to the Pie project; any ideas are welcome.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature attempt to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you would like to see.
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other contextual information or screenshots.
    validations:
      required: false
